import type { CollectionBeforeChangeHook, PayloadRequest } from 'payload'
import type { Keyword, Post } from '../../../payload-types'
import { extractLexicalText } from '../../../utilities/extractLexicalText'

type PayloadInstance = PayloadRequest['payload']

const META_DESCRIPTION_MAX_LENGTH = 155
const OLD_META_DESCRIPTION_MAX_LENGTH = 160

async function fetchFirstKeywordName(
  keywords: (number | Keyword)[] | null | undefined,
  payload: PayloadInstance,
): Promise<string | null> {
  if (!keywords?.length) return null
  const first = keywords[0]
  if (typeof first !== 'number') return first.name ?? null
  const result = await payload.find({
    collection: 'keywords',
    where: { id: { equals: first } },
    limit: 1,
    depth: 0,
  })
  return result.docs[0]?.name ?? null
}

// Format: "{keyword} — {content excerpt}" within META_DESCRIPTION_MAX_LENGTH chars.
// Falls back to plain excerpt when no keyword is set.
function buildDescription(contentText: string, keywordName: string | null): string {
  if (!keywordName) return contentText.substring(0, META_DESCRIPTION_MAX_LENGTH).trim()
  const prefix = `${keywordName} — `
  const available = META_DESCRIPTION_MAX_LENGTH - prefix.length
  if (available <= 0) return contentText.substring(0, META_DESCRIPTION_MAX_LENGTH).trim()
  return `${prefix}${contentText.substring(0, available).trim()}`
}

// Returns true if the description looks like it was auto-generated from the given content text.
// Handles old format (160-char plain excerpt), new no-keyword format (155-char plain excerpt),
// and new keyword format ("{keyword} — {content excerpt}") — without needing to know the keyword.
function looksAutoGenerated(description: string, originalContentText: string): boolean {
  if (!originalContentText) return false

  // Old format: exactly the first 160 chars of content
  if (description === originalContentText.substring(0, OLD_META_DESCRIPTION_MAX_LENGTH).trim()) {
    return true
  }

  // New format, no keyword: exactly the first 155 chars of content
  if (description === originalContentText.substring(0, META_DESCRIPTION_MAX_LENGTH).trim()) {
    return true
  }

  // New format with keyword: "{keyword} — {content excerpt}"
  // We don't know the keyword, but the content portion must be a prefix of the original text.
  const emdashIdx = description.indexOf(' — ')
  if (emdashIdx !== -1) {
    const contentPart = description.substring(emdashIdx + 3)
    if (contentPart && originalContentText.startsWith(contentPart)) {
      return true
    }
  }

  return false
}

/**
 * Auto-generates meta.description from the post body and primary keyword on every save.
 *
 * Format: "{First Keyword} — {content excerpt}", hard-limited to 155 chars.
 * Leading with the primary keyword maximises bold-match frequency in SERPs when
 * users search for that term. Falls back to a plain content excerpt when no
 * keywords are set.
 *
 * Override detection: synchronously checks if the current description looks like
 * it was auto-generated from the previously saved content (handles both old 160-char
 * and new 155-char + keyword formats). Does not require a DB fetch, making it
 * robust on every 100ms autosave. If the description was manually edited (doesn't
 * match any known auto-generated pattern), it is left alone.
 *
 * Clicking the SEO tab's "Auto Generate" link resets the description to the
 * auto-generated value, restoring auto-mode on the next save.
 */
export const syncContentToMetaDescription: CollectionBeforeChangeHook<Post> = async ({
  data,
  originalDoc,
  req: { payload },
}) => {
  if (data.postDescription) {
    return {
      ...data,
      meta: { ...data.meta, description: data.postDescription as string },
    }
  }

  if (!data.content?.root) return data

  const contentText = extractLexicalText(data.content.root)
  if (!contentText) return data

  const currentDescription = (data.meta?.description as string | undefined) ?? ''

  // Override detection: if there is an existing description and originalDoc has content,
  // check whether the current description was auto-generated. If not, the editor manually
  // wrote it — leave it alone.
  if (currentDescription && originalDoc?.content?.root) {
    const originalContentText = extractLexicalText(originalDoc.content.root)
    if (!looksAutoGenerated(currentDescription, originalContentText)) return data
  }

  const keywordName = await fetchFirstKeywordName(data.keywords, payload)
  const newDescription = buildDescription(contentText, keywordName)

  return {
    ...data,
    meta: { ...data.meta, description: newDescription },
  }
}
